### ISSUE TITLE
1.0 checklist

### ISSUE THREAD

**Issue by bmesuere** [unipept/unipept-cli#5]
List of things preventing a public 1.0 release:
bugs
- [x] bmesuere/unipept#305: show help when running without (valid) options
- [x] bmesuere/unipept#335: disable service message

features
- [x] dedicated machine for api.unipept.ugent.be
- [x] fix readme and license
- [x] bmesuere/unipept#229: installation documentation
- [x] bmesuere/unipept#257: rewrite CLI help (#6)
- [x] bmesuere/unipept#261: check if the fasta parsing is correct
- [x] add documentation to the unipept home page
- [x] bmesuere/unipept#343: add tests
- [x] #23: retry requests
- [x] #15: update batch sizes based on testing
- [x] #41: add the fasta headers to the xml and json output

All old remaining issues were moved from unipept/unipept. The old ones can be found under https://github.ugent.be/bmesuere/unipept/issues?milestone=18&state=closed

Some external people are already using the gem, so from now on a changelog should be kept.

_[Original issue](https://github.ugent.be/unipept/unipept-cli/issues/5) by @bmesuere on Fri Aug 15 2014 at 14:51._
_Closed by @bmesuere on Tue Jul 14 2015 at 14:17._

**Comment by bmesuere** [comment]
All done, 1.0 is go!


_[Original comment](https://github.ugent.be/unipept/unipept-cli/issues/5#issuecomment-19081) by @bmesuere on Tue Jul 14 2015 at 14:17._
